<?php

namespace Edukodas\Bundle\UserBundle\Repository;

/**
 * StudentTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
