<?php

namespace Edukodas\Bundle\UserBundle\Repository;

use Edukodas\Bundle\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return User[]
     */
    public function findAllStudents()
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.roles LIKE :studentRole')
            ->setParameter('studentRole', '%' . User::STUDENT_ROLE . '%')
            ->getQuery()
            ->getResult();
    }
}
