edukodas_teacher_profile:
    path:     /teacher
    defaults: { _controller: EdukodasProfileBundle:TeacherProfile:index }

edukodas_student_profile:
    path: /student/{id}
    defaults: { _controller: EdukodasProfileBundle:StudentProfile:index, id: null }
