<?php

namespace Edukodas\Bundle\TasksBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Edukodas\Bundle\TasksBundle\Entity\Course;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    /**
     * @return Course
     */
    public function getFirstCourse()
    {
        return $this
            ->createQueryBuilder('c')
            ->orderBy('c.id', 'asc')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }
}
